//
// Created by Alexis Gardin on 09/10/2018.
//

#ifndef NEURAL_NETWORK_FROM_SCRATCH_SIGMOIDWEIGHT_H
#define NEURAL_NETWORK_FROM_SCRATCH_SIGMOIDWEIGHT_H


class SigmoidWeight {

};


#endif //NEURAL_NETWORK_FROM_SCRATCH_SIGMOIDWEIGHT_H
